# NovaPlay keys file — edit and restart Enigma2. Lines: KEY=value
# These override the same keys stored in the state file.

tmdb_api_key=46b050dc88e3c52e9d1bca4b656036e4
subsource_api_key=sk_17af271fe5e6bcce4174dfdee41772fbb5c55945340961b535b2d142269530e5
opensubtitles_api_key=IKQqbvDk4ORhIGo6oWVa0ppFAtI1g8mZ
# browser_proxy=http://192.168.1.100:5000
# torrserver_url=http://127.0.0.1:8090
